-- Run this in the Supabase SQL editor (migrations on this project are drifted,
-- `supabase db push` fails).
--
-- WHAT IT IS FOR
-- The Meta Purchase event fires from the Stripe webhook, a server-to-server
-- call that carries none of the buyer's browser identity. Meta scored that
-- event 3.2 out of 10 on match quality against 8.7 for our Lead event, so most
-- purchases could not be attributed to the ad that produced them.
--
-- /api/checkout writes one row here on the way to Stripe, puts the token in
-- `client_reference_id`, and the webhook reads it back. Rows are write-once and
-- only useful for the minutes between clicking buy and Stripe settling.
--
-- Until this table exists the code degrades cleanly: no row means no token,
-- which means checkout still works and only the enrichment is lost.

create table if not exists public.checkout_attribution (
  -- The token is generated by us and travels through the Stripe URL, so it is
  -- the natural lookup key. A surrogate id would still need a unique index on
  -- this column, and the table is small and short-lived.
  token       text primary key,
  fbp         text,
  fbc         text,
  client_ip   text,
  user_agent  text,
  -- Which thing was bought, so the webhook can fire Purchase for an assessment
  -- and ProgrammeStart for an enrolment rather than one blurred event.
  product     text,
  created_at  timestamptz not null default now()
);

-- Nothing but the service role should ever read this: it holds IP addresses and
-- advertising identifiers. Enabling RLS with no policies denies anon and
-- authenticated outright, while the service-role key used by the API routes
-- bypasses RLS as normal.
alter table public.checkout_attribution enable row level security;

-- Supports the retention delete below. The primary key already covers lookups.
create index if not exists checkout_attribution_created_at_idx
  on public.checkout_attribution (created_at);

comment on table public.checkout_attribution is
  'Short-lived bridge carrying _fbp, _fbc, IP and user agent from the browser to the Stripe webhook so the Meta Purchase event can be matched. Safe to purge after a few days.';

-- OPTIONAL RETENTION, requires pg_cron.
-- These rows are worthless once the payment has settled, and they contain
-- personal data, so do not keep them.
--
-- create extension if not exists pg_cron;
-- select cron.schedule(
--   'purge-checkout-attribution',
--   '0 3 * * *',
--   $$delete from public.checkout_attribution where created_at < now() - interval '7 days'$$
-- );
